index: 597
Traceback (most recent call last):
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\yolov1_impl\train_taco.py", line 83, in <module>
    pred_boxes, target_boxes = get_bboxes(
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\yolov1_impl\utils.py", line 252, in get_bboxes
    for batch_idx, (x, labels) in enumerate(loader):
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\.venv\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\.venv\lib\site-packages\torch\utils\data\dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\.venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch 
    data = self.dataset.__getitems__(possibly_batched_index)
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\.venv\lib\site-packages\torch\utils\data\dataset.py", line 364, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\.venv\lib\site-packages\torch\utils\data\dataset.py", line 364, in <listcomp>    return [self.dataset[self.indices[idx]] for idx in indices]
  File "C:\Users\140810200030_Fauzan\Codes\Skripsi-Fauzan_Azmi_Dwicahyo\yolov1_impl\taco_dataset.py", line 79, in __getitem__
    if label_matrix[i, j, self.C] == 0:
IndexError: index 7 is out of bounds for dimension 0 with size 7
